### ISSUE TITLE
split(",")

### ISSUE THREAD

**Issue by iankigen** [Allan690/Andela_Challenge#1]
https://github.com/Allan690/Andela_Challenge/blob/bf4f621fa59fcf0552f48afd51c3fe27d16908d9/PasswordChecker.py#L2

why are you using split() here?
are you not supposed to validate only one password

**Comment by Allan690** [comment]
No, its actually a list of passwords

Your program should accept a sequence of comma separated passwords and will check them according to the above criteria. Passwords that match the criteria are to be printed, each separated by a comma

**Comment by iankigen** [comment]
Thats cool.
