### ISSUE TITLE
return

### ISSUE THREAD

**Issue by iankigen** [Allan690/Andela_Challenge#5]
https://github.com/Allan690/Andela_Challenge/blob/bf4f621fa59fcf0552f48afd51c3fe27d16908d9/PasswordChecker.py#L11

return will terminate the app, if the 1st pass is invalid then non of the other passwords will be validated.

**Comment by Allan690** [comment]
I've taken out that part of the code. What do you recommend I should have there?

**Comment by iankigen** [comment]
if you can handle it like https://github.com/Allan690/Andela_Challenge/issues/8
It will be very easy for you to test

**Comment by iankigen** [comment]
check out this short intro to TDD https://medium.freecodecamp.org/learning-to-test-with-python-997ace2d8abe
